# Generated by Django 4.2.5 on 2024-02-07 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appliances', '0004_alter_appliance_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ON', 'Bật'), ('OFF', 'Tắt'), ('VIEW', 'Xem trạng thái')], max_length=4)),
                ('status', models.BooleanField(default=False)),
                ('appliance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.appliance')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
