# Generated by Django 4.2.5 on 2024-02-07 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appliances', '0004_alter_appliance_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.appliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
