# Generated by Django 4.2.4 on 2024-04-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='about',
            field=models.TextField(blank=True, default='Em là fan cứng ba Duy', max_length=500, verbose_name='about'),
        ),
    ]
