# Generated by Django 4.2.4 on 2024-04-17 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='member_files/None/')),
                ('features', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='members.member')),
            ],
        ),
    ]
