# Generated by Django 5.0.4 on 2024-04-25 07:49

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_memberfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberfile",
            name="file",
            field=models.FileField(
                upload_to=members.models.member_audio_directory_path
            ),
        ),
    ]
