# Generated by Django 4.2.5 on 2024-02-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_created_at_alter_newuser_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
