# -*- coding: utf-8 -*-
"""Regular Expression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12sn3QiqJhw0nJOIO5TPxAnjtxZBzarMR
"""

import re

def phan_tich_cau(c):
    pattern = re.compile(r'(bật|tắt|mở|đóng|tăng|giảm|đo)\s(đèn|quạt|cửa|cửa\s+sổ|nhiệt độ|độ ẩm|nhiệt độ độ ẩm)\s(?:trong|ngoài|bên|ở\s(trong\s)?)?\s?(phòng khách|nhà bếp|garage|ga ra|chính|(?:phòng ngủ (?:ba mẹ|con cái|trẻ em)))')

    match = pattern.search(c)

    if match:
        action = match.group(1)
        device = match.group(2)
        room = match.group(4)  # Sử dụng group(4) để trích xuất phòng
        return action, device, room
    else:
        return None

chuoi = input()

# Phân tích câu
result = phan_tich_cau(chuoi)

# Hiển thị kết quả
if result:
    action, device, room = result
    print(f"{action} {device} {room}")
else:
    print("Không tìm thấy.")