# Generated by Django 4.2.5 on 2024-02-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('appliance_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('humidity', models.FloatField(default=0)),
                ('temparature', models.FloatField(default=0)),
            ],
        ),
    ]
