# Generated by Django 4.2.5 on 2024-02-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0003_alter_appliance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
